/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualisasiRouteImport } from './routes/visualisasi'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVisualisasiRouteImport } from './routes/admin.visualisasi'
import { Route as AdminPetaRouteImport } from './routes/admin.peta'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFormRouteImport } from './routes/admin.form'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBencanaRouteImport } from './routes/admin.bencana'
import { Route as AdminAnalisisRouteImport } from './routes/admin.analisis'

const VisualisasiRoute = VisualisasiRouteImport.update({
  id: '/visualisasi',
  path: '/visualisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisualisasiRoute = AdminVisualisasiRouteImport.update({
  id: '/admin/visualisasi',
  path: '/admin/visualisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPetaRoute = AdminPetaRouteImport.update({
  id: '/admin/peta',
  path: '/admin/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/admin/pengaturan',
  path: '/admin/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormRoute = AdminFormRouteImport.update({
  id: '/admin/form',
  path: '/admin/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBencanaRoute = AdminBencanaRouteImport.update({
  id: '/admin/bencana',
  path: '/admin/bencana',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalisisRoute = AdminAnalisisRouteImport.update({
  id: '/admin/analisis',
  path: '/admin/analisis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/laporan': typeof LaporanRoute
  '/peta': typeof PetaRoute
  '/visualisasi': typeof VisualisasiRoute
  '/admin/analisis': typeof AdminAnalisisRoute
  '/admin/bencana': typeof AdminBencanaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/peta': typeof AdminPetaRoute
  '/admin/visualisasi': typeof AdminVisualisasiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/laporan': typeof LaporanRoute
  '/peta': typeof PetaRoute
  '/visualisasi': typeof VisualisasiRoute
  '/admin/analisis': typeof AdminAnalisisRoute
  '/admin/bencana': typeof AdminBencanaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/peta': typeof AdminPetaRoute
  '/admin/visualisasi': typeof AdminVisualisasiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/laporan': typeof LaporanRoute
  '/peta': typeof PetaRoute
  '/visualisasi': typeof VisualisasiRoute
  '/admin/analisis': typeof AdminAnalisisRoute
  '/admin/bencana': typeof AdminBencanaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/peta': typeof AdminPetaRoute
  '/admin/visualisasi': typeof AdminVisualisasiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/laporan'
    | '/peta'
    | '/visualisasi'
    | '/admin/analisis'
    | '/admin/bencana'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/form'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/peta'
    | '/admin/visualisasi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/laporan'
    | '/peta'
    | '/visualisasi'
    | '/admin/analisis'
    | '/admin/bencana'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/form'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/peta'
    | '/admin/visualisasi'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/laporan'
    | '/peta'
    | '/visualisasi'
    | '/admin/analisis'
    | '/admin/bencana'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/form'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/peta'
    | '/admin/visualisasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LaporanRoute: typeof LaporanRoute
  PetaRoute: typeof PetaRoute
  VisualisasiRoute: typeof VisualisasiRoute
  AdminAnalisisRoute: typeof AdminAnalisisRoute
  AdminBencanaRoute: typeof AdminBencanaRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminFormRoute: typeof AdminFormRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPetaRoute: typeof AdminPetaRoute
  AdminVisualisasiRoute: typeof AdminVisualisasiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualisasi': {
      id: '/visualisasi'
      path: '/visualisasi'
      fullPath: '/visualisasi'
      preLoaderRoute: typeof VisualisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visualisasi': {
      id: '/admin/visualisasi'
      path: '/admin/visualisasi'
      fullPath: '/admin/visualisasi'
      preLoaderRoute: typeof AdminVisualisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peta': {
      id: '/admin/peta'
      path: '/admin/peta'
      fullPath: '/admin/peta'
      preLoaderRoute: typeof AdminPetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/form': {
      id: '/admin/form'
      path: '/admin/form'
      fullPath: '/admin/form'
      preLoaderRoute: typeof AdminFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bencana': {
      id: '/admin/bencana'
      path: '/admin/bencana'
      fullPath: '/admin/bencana'
      preLoaderRoute: typeof AdminBencanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analisis': {
      id: '/admin/analisis'
      path: '/admin/analisis'
      fullPath: '/admin/analisis'
      preLoaderRoute: typeof AdminAnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LaporanRoute: LaporanRoute,
  PetaRoute: PetaRoute,
  VisualisasiRoute: VisualisasiRoute,
  AdminAnalisisRoute: AdminAnalisisRoute,
  AdminBencanaRoute: AdminBencanaRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportRoute: AdminExportRoute,
  AdminFormRoute: AdminFormRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPetaRoute: AdminPetaRoute,
  AdminVisualisasiRoute: AdminVisualisasiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
